version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/ideal_parking_dev
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./.mongo_test_data:/data/db
